### ISSUE TITLE
Reduce repo size

### ISSUE THREAD

**Issue by ValdasK** [DATA-DOG/symfony-force#13]
Cloning repository is waste of space, as images and gifs take over 10M of space. Remove them, rewrite history purging them and move those to remote servers.

Due space issues, new projects have to clear git history, making rebases imposible.

**Comment by l3pp4rd** [comment]
These are images in could to save some repo space

![starwars](https://cloud.githubusercontent.com/assets/132389/10692485/9543db14-799a-11e5-9779-2a0ec870752f.gif)
![screenshot](https://cloud.githubusercontent.com/assets/132389/10692496/a3646344-799a-11e5-9fd5-ec7d33cf9d91.png)
